
final List<Map<String, dynamic>> mockDestinationsData = [
  {
    'id': 'DST-KER',
    'name': 'Kerala',
    'state': 'Kerala',
    'country': 'India',
    'image': 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    'hotel_count': 17,
    'tagline': "God's Own Country — Backwaters, tea hills & beaches",
  },
  {
    'id': 'DST-KAR',
    'name': 'Karnataka',
    'state': 'Karnataka',
    'country': 'India',
    'image': 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&q=80',
    'hotel_count': 11,
    'tagline': 'Royal palaces, aromatic coffee estates & tech pulse',
  },
  {
    'id': 'DST-TN',
    'name': 'Tamil Nadu',
    'state': 'Tamil Nadu',
    'country': 'India',
    'image': 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80',
    'hotel_count': 8,
    'tagline': 'Dravidian architecture, cool Nilgiris & French colonial coasts',
  },
  {
    'id': 'DST-KOC',
    'name': 'Kochi',
    'state': 'Kerala',
    'country': 'India',
    'image': 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&q=80',
    'hotel_count': 5,
    'tagline': 'Island backwaters, spice markets & colonial charm',
  },
  {
    'id': 'DST-BLR',
    'name': 'Bengaluru',
    'state': 'Karnataka',
    'country': 'India',
    'image': 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&q=80',
    'hotel_count': 4,
    'tagline': 'Silicon capital luxury, gardens & vibrant dining',
  },
  {
    'id': 'DST-MUN',
    'name': 'Munnar',
    'state': 'Kerala',
    'country': 'India',
    'image': 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
    'hotel_count': 4,
    'tagline': 'Misty emerald tea estates & refreshing mountain breeze',
  },
  {
    'id': 'DST-OOT',
    'name': 'Ooty',
    'state': 'Tamil Nadu',
    'country': 'India',
    'image': 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800&q=80',
    'hotel_count': 3,
    'tagline': 'Queen of Hill Stations, heritage cottages & pine valleys',
  },
  {
    'id': 'DST-CRG',
    'name': 'Coorg',
    'state': 'Karnataka',
    'country': 'India',
    'image': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    'hotel_count': 3,
    'tagline': 'Fragrant coffee plantations, cascading falls & Kodava warmth',
  },
  {
    'id': 'DST-WAY',
    'name': 'Wayanad',
    'state': 'Kerala',
    'country': 'India',
    'image': 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
    'hotel_count': 3,
    'tagline': 'Dense rainforest reserves, spice valleys & nature treehouses',
  },
];

final List<Map<String, dynamic>> mockHotelsData = [

  {
    'id': 'HTL-KER-001',
    'name': 'Grand Hyatt Kochi Bolgatty',
    'destination': 'Kochi',
    'city': 'Kochi',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Mulavukad, Bolgatty Island, Kochi, Kerala 682504',
    'rating': 4.8,
    'review_count': 842,
    'price_per_night': 9499.0,
    'original_price': 12000.0,
    'images': [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
    ],
    'description':
        'Commanding panoramic views over Lake Vembanad on Bolgatty Island, Grand Hyatt Kochi is an oasis of luxury featuring sprawling waterfront lawns, a traditional Santata Ayurveda Spa, multiple fine-dining restaurants, and international marina access.',
    'amenities': [
      {'id': 'a1', 'name': 'Free High-Speed WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Waterfront Infinity Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Santata Ayurvedic Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Malabar Cafe & Thai Soul', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Valet Parking', 'icon': 'parking'},
      {'id': 'a6', 'name': 'Fitness Center & Marina', 'icon': 'fitness'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-001-1',
        'hotel_id': 'HTL-KER-001',
        'name': 'Grand Lake View Room',
        'description': 'Elegant room with floor-to-ceiling glass windows framing peaceful Vembanad Lake and city skyline.',
        'price_per_night': 9499.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 450,
        'amenities': ['Lake View', 'Bathtub', 'Balcony', 'Smart TV'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-KER-001-2',
        'hotel_id': 'HTL-KER-001',
        'name': 'Executive Waterfront Suite',
        'description': 'Expansive living room, dining area, walk-in closet, and private sunset observation terrace.',
        'price_per_night': 14999.0,
        'capacity': 3,
        'bed_type': '1 King Bed + 1 Daybed',
        'size_sq_ft': 880,
        'amenities': ['Executive Lounge Access', 'Private Jacuzzi', 'Butler Service', 'Complimentary High Tea'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to check-in. 1 night charge afterwards.',
    'latitude': 9.9863,
    'longitude': 76.2694,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-KER-002',
    'name': 'Fragrant Nature Munnar',
    'destination': 'Munnar',
    'city': 'Munnar',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Pothamedu, Bisonvalley Road, Munnar, Kerala 685565',
    'rating': 4.7,
    'review_count': 612,
    'price_per_night': 5899.0,
    'original_price': 7500.0,
    'images': [
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    ],
    'description':
        'Perched dramatically on the slopes of Pothamedu with uninterrupted views of mist-covered tea gardens, Fragrant Nature Munnar blends British colonial aesthetics with warm Kerala hospitality. Cozy fireplaces warm the rooms as clouds drift past your balcony.',
    'amenities': [
      {'id': 'a1', 'name': 'Complimentary High-Speed WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Fireplace in Every Room', 'icon': 'check'},
      {'id': 'a3', 'name': 'Prana Wellness Ayurveda', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Glasshouse All-Day Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Guided Tea Plantation Walks', 'icon': 'check'},
      {'id': 'a6', 'name': 'Mountain Amphitheatre', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-002-1',
        'hotel_id': 'HTL-KER-002',
        'name': 'Tropic Green Valley Room',
        'description': 'Handcrafted timber flooring, working natural fireplace, and private balcony overlooking emerald tea valleys.',
        'price_per_night': 5899.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 400,
        'amenities': ['Valley View', 'Fireplace', 'Balcony', 'Herbal Tea Station'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
      {
        'id': 'RM-KER-002-2',
        'hotel_id': 'HTL-KER-002',
        'name': 'Moonlight Mountain Suite',
        'description': 'Spacious attic suite with skylights for stargazing, jacuzzi overlooking the peaks, and living lounge.',
        'price_per_night': 8999.0,
        'capacity': 3,
        'bed_type': '1 King Bed + 1 Sofa Bed',
        'size_sq_ft': 680,
        'amenities': ['Private Jacuzzi', 'Fireplace', 'Mountain Panorama', 'Welcome Fruit Basket'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 72 hours before arrival.',
    'latitude': 10.0489,
    'longitude': 77.0595,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-KER-003',
    'name': 'Vythiri Village Resort',
    'destination': 'Wayanad',
    'city': 'Wayanad',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'NH 212, Near Vythiri Town, Wayanad, Kerala 673576',
    'rating': 4.6,
    'review_count': 528,
    'price_per_night': 6499.0,
    'original_price': 8200.0,
    'images': [
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
    ],
    'description':
        'Set across 22 acres of pristine Western Ghats rainforest in Wayanad, Vythiri Village features an iconic wooden suspension bridge, natural stream bathing, organic spice gardens, and authentic treehouse stays enveloped by tropical mist.',
    'amenities': [
      {'id': 'a1', 'name': 'High-Speed WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Ozone Swimming Pool & Waterfall', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Nawa Ayurvedic Wellness Centre', 'icon': 'spa'},
      {'id': 'a4', 'name': 'SpiceBowl Multi-Cuisine Restaurant', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Zip Line & Adventure Park', 'icon': 'check'},
      {'id': 'a6', 'name': 'Campfire with Live Classical Music', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-003-1',
        'hotel_id': 'HTL-KER-003',
        'name': 'Deluxe Forest Cottage',
        'description': 'Quaint stone-and-timber cottage shaded by ancient rainforest trees with private sit-out deck.',
        'price_per_night': 6499.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 480,
        'amenities': ['Stream View', 'Veranda', 'Rain Shower', 'Organic Toiletries'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=800&q=80'],
      },
      {
        'id': 'RM-KER-003-2',
        'hotel_id': 'HTL-KER-003',
        'name': 'Luxury Tree House Villa',
        'description': 'Elevated high in the natural rainforest canopy with thatch roof, teak interiors, and birdwatching deck.',
        'price_per_night': 11499.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 600,
        'amenities': ['Canopy Panorama', 'Private Deck', 'Solar Powered Hot Water', 'Complimentary Plantation Tour'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to arrival.',
    'latitude': 11.5544,
    'longitude': 76.0416,
    'is_popular': false,
    'is_featured': true,
  },
  {
    'id': 'HTL-KER-004',
    'name': 'The Raviz Ashtamudi & Backwaters',
    'destination': 'Alappuzha',
    'city': 'Alappuzha',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Thevally, Mathilil PO, Alappuzha Region, Kerala 691601',
    'rating': 4.7,
    'review_count': 490,
    'price_per_night': 7899.0,
    'original_price': 9999.0,
    'images': [
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    ],
    'description':
        'A tribute to traditional Travancore architectural splendor designed by legendary architect Laurie Baker, this peaceful backwater sanctuary sits where gentle lagoons meet coconut groves. Enjoy private Kettuvallam houseboats and authentic Karimeen delicacies.',
    'amenities': [
      {'id': 'a1', 'name': 'Complimentary WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Lakeside Infinity Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ayuraviz Heritage Wellness Clinic', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Floating Sunset Seafood Grill', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Private Houseboat Cruises', 'icon': 'check'},
      {'id': 'a6', 'name': 'Speedboat & Kayaking Club', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-004-1',
        'hotel_id': 'HTL-KER-004',
        'name': 'Heritage Lagoon View Room',
        'description': 'Carved teakwood furnishings, traditional brass fixtures, and uninterrupted vistas of serene backwater channels.',
        'price_per_night': 7899.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 520,
        'amenities': ['Backwater View', 'Teak Balcony', 'Handmade Brass Urli', 'Tea Brewer'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-KER-004-2',
        'hotel_id': 'HTL-KER-004',
        'name': 'Traditional Private Houseboat Suite',
        'description': 'Fully staffed luxury bedroom aboard an authentic handcrafted Kettuvallam anchored along the calm lagoon.',
        'price_per_night': 13999.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 650,
        'amenities': ['Dedicated Chef', 'Sunset Cruise Included', 'Air Conditioned', 'Open-Deck Dining'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to check-in.',
    'latitude': 9.4981,
    'longitude': 76.3388,
    'is_popular': true,
    'is_featured': false,
  },
  {
    'id': 'HTL-KER-005',
    'name': 'Gateway Hotel Marine Drive Calicut',
    'destination': 'Kozhikode',
    'city': 'Kozhikode',
    'state': 'Kerala',
    'star_rating': 4,
    'address': 'PT Usha Road, Kozhikode, Kerala 673032',
    'rating': 4.4,
    'review_count': 348,
    'price_per_night': 3899.0,
    'original_price': 4800.0,
    'images': [
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Located in the heart of Calicut near the historic beach and vibrant Mananchira Square, The Gateway Hotel offers contemporary comfort, famed Malabar biryani feasts, and relaxing poolside gardens for business and leisure travelers alike.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast Free WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Outdoor Swimming Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ayurvedic Massage Centre', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Cape Comorin Malabar Restaurant', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Free Covered Parking', 'icon': 'parking'},
      {'id': 'a6', 'name': 'Gym & Business Center', 'icon': 'fitness'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-005-1',
        'hotel_id': 'HTL-KER-005',
        'name': 'Standard City View Room',
        'description': 'Smartly appointed room with ergonomic workspace, plush queen bedding, and premium bathroom fittings.',
        'price_per_night': 3899.0,
        'capacity': 2,
        'bed_type': '1 Queen Bed',
        'size_sq_ft': 320,
        'amenities': ['City View', 'Work Desk', 'High Speed WiFi', 'Coffee Maker'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-KER-005-2',
        'hotel_id': 'HTL-KER-005',
        'name': 'Executive Superior Room',
        'description': 'Spacious room with pool view, lounge armchair, and complimentary evening coffee with Calicut banana chips.',
        'price_per_night': 5299.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 420,
        'amenities': ['Pool View', 'Bathtub', 'Welcome Sweets', 'Late Check-out'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 24 hours prior to check-in.',
    'latitude': 11.2588,
    'longitude': 75.7804,
    'is_popular': false,
    'is_featured': false,
  },
  {
    'id': 'HTL-KER-006',
    'name': 'Clifftop Beach Sanctuary',
    'destination': 'Varkala',
    'city': 'Varkala',
    'state': 'Kerala',
    'star_rating': 4,
    'address': 'North Cliff, Kurakkanni, Varkala, Kerala 695141',
    'rating': 4.5,
    'review_count': 415,
    'price_per_night': 3499.0,
    'original_price': 4500.0,
    'images': [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    ],
    'description':
        'Perched majestically atop Varkala’s dramatic red laterite cliffs, this bohemian luxury sanctuary offers open-air sea-breeze terraces, sunset yoga pavilions, direct path to Papanasam beach, and restorative herbal oil therapies.',
    'amenities': [
      {'id': 'a1', 'name': 'Free High-Speed WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Ocean View Plunge Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Daily Rooftop Sunrise Yoga', 'icon': 'check'},
      {'id': 'a4', 'name': 'Tibetan & Kerala Seafood Bistro', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Direct Beach Trail Access', 'icon': 'check'},
      {'id': 'a6', 'name': 'Ayurvedic Pulse Assessment', 'icon': 'spa'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-006-1',
        'hotel_id': 'HTL-KER-006',
        'name': 'Cliff Ocean Breeze Room',
        'description': 'Charming coastal room with terracotta tiles, white linen four-poster bed, and Arabian sea sunset balcony.',
        'price_per_night': 3499.0,
        'capacity': 2,
        'bed_type': '1 Queen Bed',
        'size_sq_ft': 350,
        'amenities': ['Sea View', 'Balcony', 'Ceiling Fan & AC', 'Handmade Hammock'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
      {
        'id': 'RM-KER-006-2',
        'hotel_id': 'HTL-KER-006',
        'name': 'Panoramic Cliff Honeymoon Chalet',
        'description': 'Corner chalet with 180-degree coastal horizon view, open-sky rain shower, and private hammock deck.',
        'price_per_night': 5999.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 520,
        'amenities': ['180° Ocean View', 'Open-Air Shower', 'Sun Deck', 'Fruit & Wine Basket'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours before check-in.',
    'latitude': 8.7379,
    'longitude': 76.7163,
    'is_popular': true,
    'is_featured': false,
  },
  {
    'id': 'HTL-KER-007',
    'name': 'Spice Village Thekkady',
    'destination': 'Thekkady',
    'city': 'Thekkady',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Kottayam - Kumily Road, Thekkady, Kerala 685509',
    'rating': 4.8,
    'review_count': 576,
    'price_per_night': 6199.0,
    'original_price': 7900.0,
    'images': [
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    ],
    'description':
        'Modeled as a traditional Mannan tribal village bordering the Periyar Tiger Reserve, Spice Village is an eco-luxury masterpiece with elephant-grass thatched roofs, spice-scented orchards, and dusk nature walks guided by naturalist tribals.',
    'amenities': [
      {'id': 'a1', 'name': 'Free WiFi in Lobby & Lounges', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Mountain Spring Fed Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': '50-Acre Organic Spice Garden', 'icon': 'check'},
      {'id': 'a4', 'name': '50-Mile Farm-to-Table Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Periyar Bamboo Rafting Assistance', 'icon': 'check'},
      {'id': 'a6', 'name': 'Classical Kathakali Shows', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-007-1',
        'hotel_id': 'HTL-KER-007',
        'name': 'Standard Spice Garden Villa',
        'description': 'Thatched cottage with terracotta tiled floor, natural coir mats, and veranda opening directly into clove trees.',
        'price_per_night': 6199.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 420,
        'amenities': ['Garden View', 'Veranda', 'Rain Shower', 'Organic Herbal Tea'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=800&q=80'],
      },
      {
        'id': 'RM-KER-007-2',
        'hotel_id': 'HTL-KER-007',
        'name': 'Eco Deluxe Plantation Suite',
        'description': 'Private stand-alone tribal cottage with expansive outdoor garden courtyard, reading lounge, and bird bath.',
        'price_per_night': 8999.0,
        'capacity': 3,
        'bed_type': '1 King Bed + 1 Rollaway',
        'size_sq_ft': 640,
        'amenities': ['Private Courtyard', 'Natural Stone Bath', 'Binoculars & Bird Guide', 'Organic Fruit Basket'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 72 hours before arrival.',
    'latitude': 9.6031,
    'longitude': 77.1689,
    'is_popular': false,
    'is_featured': true,
  },
  {
    'id': 'HTL-KER-008',
    'name': 'Uday Samudra Leisure Beach Resort',
    'destination': 'Thiruvananthapuram',
    'city': 'Thiruvananthapuram',
    'state': 'Kerala',
    'star_rating': 4,
    'address': 'GV Raja Road, Samudra Beach, Kovalam, Trivandrum, Kerala 695527',
    'rating': 4.3,
    'review_count': 680,
    'price_per_night': 4299.0,
    'original_price': 5600.0,
    'images': [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Steps away from the golden sands of Samudra Beach in Kovalam, Uday Samudra boasts 3 sprawling outdoor swimming pools, beachfront dining under coconut palms, and an internationally accredited Ayurveda wellness retreat.',
    'amenities': [
      {'id': 'a1', 'name': 'Free WiFi in All Rooms', 'icon': 'wifi'},
      {'id': 'a2', 'name': '3 Lagoon Swimming Pools', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ayur Ashram Traditional Therapy', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Grass Hopper Beach Cafe', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Free Beach Umbrella & Loungers', 'icon': 'check'},
      {'id': 'a6', 'name': 'Airport Shuttle Service', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-008-1',
        'hotel_id': 'HTL-KER-008',
        'name': 'Atrium Pool View Room',
        'description': 'Bright room opening to the tranquil central pool courtyard with private balcony and modern bathroom.',
        'price_per_night': 4299.0,
        'capacity': 2,
        'bed_type': '1 King Bed or 2 Twins',
        'size_sq_ft': 360,
        'amenities': ['Pool View', 'Balcony', 'Mini Fridge', 'Coffee Station'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-KER-008-2',
        'hotel_id': 'HTL-KER-008',
        'name': 'Ocean Wave Front Suite',
        'description': 'Direct sea-facing suite with crashing surf audio, huge balcony, sun beds, and whirlpool bath.',
        'price_per_night': 7499.0,
        'capacity': 3,
        'bed_type': '1 King Bed',
        'size_sq_ft': 580,
        'amenities': ['Direct Sea View', 'Private Jacuzzi', 'Sunbed Balcony', 'Complimentary Breakfast'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to check-in.',
    'latitude': 8.4022,
    'longitude': 76.9787,
    'is_popular': false,
    'is_featured': false,
  },

  {
    'id': 'HTL-KAR-001',
    'name': 'The Leela Palace Bengaluru',
    'destination': 'Bengaluru',
    'city': 'Bengaluru',
    'state': 'Karnataka',
    'star_rating': 5,
    'address': '23 Old Airport Road, HAL 2nd Stage, Kodihalli, Bengaluru, Karnataka 560008',
    'rating': 4.9,
    'review_count': 1250,
    'price_per_night': 15499.0,
    'original_price': 19500.0,
    'images': [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Standing amidst 7 acres of lush gardens with cascading waterfalls, The Leela Palace Bengaluru mirrors the architectural grandeur of the Royal Palace of Mysuru. Hand-woven carpets, gold-leaf domes, crystal chandeliers, and bespoke butler service provide unprecedented luxury.',
    'amenities': [
      {'id': 'a1', 'name': 'High-Speed Fiber WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Heated Garden Swimming Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'The Spa by ESPA', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Jamavar & Le Cirque Signature Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Chauffeured Luxury Fleet', 'icon': 'parking'},
      {'id': 'a6', 'name': '24-Hour Butler & Concierge', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-001-1',
        'hotel_id': 'HTL-KAR-001',
        'name': 'Deluxe Royal Palace Room',
        'description': 'Opulent room with mother-of-pearl inlays, custom Italian marble bath, and garden patio view.',
        'price_per_night': 15499.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 540,
        'amenities': ['Garden View', 'Marble Bath', 'Bose Soundbar', 'Pillow Menu'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-KAR-001-2',
        'hotel_id': 'HTL-KAR-001',
        'name': 'Executive Maharaja Suite',
        'description': 'Palatial suite with distinct drawing room, gold-leaf ceilings, Jacuzzi bath, and Royal Club access.',
        'price_per_night': 26999.0,
        'capacity': 3,
        'bed_type': '1 Four-Poster King Bed',
        'size_sq_ft': 1100,
        'amenities': ['Royal Club Access', 'Dedicated Butler', 'Cocktail Hour', 'Airport Transfer'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours before check-in. Non-refundable afterwards.',
    'latitude': 12.9606,
    'longitude': 77.6484,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-KAR-002',
    'name': 'Lalitha Mahal Palace Hotel',
    'destination': 'Mysuru',
    'city': 'Mysuru',
    'state': 'Karnataka',
    'star_rating': 5,
    'address': 'Lalitha Mahal Nagar, Siddhartha Layout, Mysuru, Karnataka 570028',
    'rating': 4.6,
    'review_count': 724,
    'price_per_night': 6799.0,
    'original_price': 8500.0,
    'images': [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
    ],
    'description':
        'Built in 1921 by the Maharaja of Mysore for the Viceroy of India, this gleaming white Italian Renaissance palace hotel features a majestic central dome, sweeping Italian marble staircases, and historic royal ballroom banquets.',
    'amenities': [
      {'id': 'a1', 'name': 'Free Palace WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Royal Garden Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Heritage Spa Treatments', 'icon': 'spa'},
      {'id': 'a4', 'name': 'The Royal Ballroom Restaurant', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Billiards & Heritage Tennis Court', 'icon': 'check'},
      {'id': 'a6', 'name': 'Complimentary Palace Heritage Tour', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-002-1',
        'hotel_id': 'HTL-KAR-002',
        'name': 'Heritage Royal Turret Room',
        'description': 'High-ceilinged chamber with antique colonial furniture, period brass hardware, and views of Chamundi Hill.',
        'price_per_night': 6799.0,
        'capacity': 2,
        'bed_type': '1 King Heritage Bed',
        'size_sq_ft': 480,
        'amenities': ['Chamundi Hill View', 'Original Marble Fireplace', 'Clawfoot Bathtub', 'High Ceilings'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
      {
        'id': 'RM-KAR-002-2',
        'hotel_id': 'HTL-KAR-002',
        'name': 'The Viceroy Royal Suite',
        'description': 'Historical suite once occupied by British royalty with private dining salon, antique chandeliers, and veranda.',
        'price_per_night': 12999.0,
        'capacity': 3,
        'bed_type': '1 King Heritage Bed',
        'size_sq_ft': 950,
        'amenities': ['Private Dining Salon', 'Butler Service', 'Antique Furniture', 'Champagne Breakfast'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to arrival.',
    'latitude': 12.3023,
    'longitude': 76.6917,
    'is_popular': false,
    'is_featured': true,
  },
  {
    'id': 'HTL-KAR-003',
    'name': 'Evolve Back Chikkana Halli Estate',
    'destination': 'Coorg',
    'city': 'Madikeri',
    'state': 'Karnataka',
    'star_rating': 5,
    'address': 'Karadigodu Post, Siddapur, Coorg, Karnataka 571253',
    'rating': 4.9,
    'review_count': 892,
    'price_per_night': 16899.0,
    'original_price': 21000.0,
    'images': [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    ],
    'description':
        'Set on a working 300-acre coffee and spice plantation, Evolve Back Coorg transports you into the gentility of the planter’s life. Private pool villas, Kodava architecture, and lake-side dining deliver an unmatched wilderness retreat.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast WiFi in Villas', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Infinity Plantation Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Vaidyasala Ayurvedic Sanctuary', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Granary & Peppercorn Specialty Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Coffee Plantation Jeep Safaris', 'icon': 'check'},
      {'id': 'a6', 'name': 'Coracle Lake Rides & Birdwatching', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-003-1',
        'hotel_id': 'HTL-KAR-003',
        'name': 'Heritage Plantation Pool Villa',
        'description': 'Private enclosed courtyard villa with individual temperature-controlled plunge pool and day bed.',
        'price_per_night': 16899.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 750,
        'amenities': ['Private Pool', 'Courtyard', 'Stone Tub', 'Espresso Machine'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=800&q=80'],
      },
      {
        'id': 'RM-KAR-003-2',
        'hotel_id': 'HTL-KAR-003',
        'name': 'Lily Pool Cottage',
        'description': 'Spacious timber cottage looking out onto a tranquil lily pond with private gazebo and outdoor day lounge.',
        'price_per_night': 21499.0,
        'capacity': 3,
        'bed_type': '1 King Bed',
        'size_sq_ft': 900,
        'amenities': ['Lily Pond View', 'Gazebo Lounge', 'Personal Butler', 'Plantation Tour'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 5 days before check-in.',
    'latitude': 12.3168,
    'longitude': 75.8753,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-KAR-004',
    'name': 'The Gateway Hotel Old Port Road',
    'destination': 'Mangaluru',
    'city': 'Mangaluru',
    'state': 'Karnataka',
    'star_rating': 4,
    'address': 'Old Port Road, Bunder, Mangaluru, Karnataka 575001',
    'rating': 4.4,
    'review_count': 398,
    'price_per_night': 3699.0,
    'original_price': 4600.0,
    'images': [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    ],
    'description':
        'Overlooking the picturesque confluence of the Gurupura and Netravati rivers, The Gateway Hotel Mangaluru blends coastal elegance with the best of coastal Tuluva hospitality, offering signature Ghee Roast seafood delicacies and pool views.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'River-Facing Swimming Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ayurvedic Wellness Massages', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Cardamom Mangalorean Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Free Parking with EV Charger', 'icon': 'parking'},
      {'id': 'a6', 'name': 'Fitness Gym', 'icon': 'fitness'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-004-1',
        'hotel_id': 'HTL-KAR-004',
        'name': 'Standard Coastal Room',
        'description': 'Contemporary room with timber accents, comfortable queen bed, and view of the active port waters.',
        'price_per_night': 3699.0,
        'capacity': 2,
        'bed_type': '1 Queen Bed',
        'size_sq_ft': 340,
        'amenities': ['River/Port View', 'Work Station', 'Tea/Coffee Maker', 'Rain Shower'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-KAR-004-2',
        'hotel_id': 'HTL-KAR-004',
        'name': 'River View Executive Suite',
        'description': 'Corner suite with wide panoramic views of the river confluence, private lounge, and whirlpool bath.',
        'price_per_night': 5899.0,
        'capacity': 3,
        'bed_type': '1 King Bed',
        'size_sq_ft': 540,
        'amenities': ['Panoramic River View', 'Living Room', 'Bathtub', 'Welcome Cocktail'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 24 hours prior to check-in.',
    'latitude': 12.8628,
    'longitude': 74.8361,
    'is_popular': false,
    'is_featured': false,
  },
  {
    'id': 'HTL-KAR-005',
    'name': 'Paradise Isle Beach Resort',
    'destination': 'Udupi',
    'city': 'Udupi',
    'state': 'Karnataka',
    'star_rating': 3,
    'address': 'Malpe Beach, Udupi, Karnataka 576108',
    'rating': 4.2,
    'review_count': 286,
    'price_per_night': 2799.0,
    'original_price': 3500.0,
    'images': [
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80',
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    ],
    'description':
        'Located directly on the silver sands of Malpe Beach facing the Arabian Sea and St. Mary’s Island, Paradise Isle offers beachfront water sports, coastal Udupi vegetarian feasts, and front-row seats to glorious ocean sunsets.',
    'amenities': [
      {'id': 'a1', 'name': 'Free WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Beachfront Swimming Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ocean Deck Multi-Cuisine Cafe', 'icon': 'restaurant'},
      {'id': 'a4', 'name': 'Direct Beach Step Access', 'icon': 'check'},
      {'id': 'a5', 'name': 'St. Mary’s Island Ferry Desk', 'icon': 'check'},
      {'id': 'a6', 'name': 'Free Car Parking', 'icon': 'parking'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-005-1',
        'hotel_id': 'HTL-KAR-005',
        'name': 'Standard Sea View Room',
        'description': 'Bright beachfront room with sliding glass door leading to a personal ocean-facing sit-out balcony.',
        'price_per_night': 2799.0,
        'capacity': 2,
        'bed_type': '1 Double Bed',
        'size_sq_ft': 310,
        'amenities': ['Sea View', 'Balcony', 'Air Conditioning', 'Satellite TV'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
      {
        'id': 'RM-KAR-005-2',
        'hotel_id': 'HTL-KAR-005',
        'name': 'Deluxe Beachfront Cottage',
        'description': 'Independent thatched cottage right on the sand with sun lounger patio and unobstructed wave views.',
        'price_per_night': 4499.0,
        'capacity': 3,
        'bed_type': '1 King Bed',
        'size_sq_ft': 450,
        'amenities': ['Beach Front', 'Private Patio', 'Hammock', 'Complimentary Breakfast'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to arrival.',
    'latitude': 13.3512,
    'longitude': 74.7032,
    'is_popular': false,
    'is_featured': false,
  },
  {
    'id': 'HTL-KAR-006',
    'name': 'The Serai Chikkamagaluru',
    'destination': 'Chikkamagaluru',
    'city': 'Chikkamagaluru',
    'state': 'Karnataka',
    'star_rating': 5,
    'address': 'Mugthihalli Post, KM Road, Chikkamagaluru, Karnataka 577133',
    'rating': 4.8,
    'review_count': 540,
    'price_per_night': 12499.0,
    'original_price': 15500.0,
    'images': [
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    ],
    'description':
        'Nestled in the birthplace of Indian coffee against the dramatic backdrop of the Mullayanagiri peak, The Serai offers private pool villas secluded within 70 acres of Arabica and Robusta coffee plantations with private glass gazebos.',
    'amenities': [
      {'id': 'a1', 'name': 'High-Speed Estate WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Private Villa Pools & Lap Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Oma Spa with Coffee Scrub Therapy', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Odyssey Multi-Cuisine & Pool Bar', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Trek to Mullayanagiri Peak Assistance', 'icon': 'check'},
      {'id': 'a6', 'name': 'Coffee Cupping & Tasting Sessions', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-006-1',
        'hotel_id': 'HTL-KAR-006',
        'name': 'Estate Villa with Private Plunge Pool',
        'description': 'Private sanctuary villa featuring a secluded swimming pool, glass-walled bedroom, and open sun deck.',
        'price_per_night': 12499.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 680,
        'amenities': ['Private Pool', 'Coffee Plantation View', 'Open Shower', 'Espresso Bar'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=800&q=80'],
      },
      {
        'id': 'RM-KAR-006-2',
        'hotel_id': 'HTL-KAR-006',
        'name': 'The Residence Presidential Two-Tier Villa',
        'description': 'Two-story private pool mansion with master bedroom, gazebo, private dining terrace, and estate panorama.',
        'price_per_night': 19999.0,
        'capacity': 4,
        'bed_type': '2 King Beds',
        'size_sq_ft': 1300,
        'amenities': ['Private Lap Pool', 'Gazebo Lounge', 'Personal Chef on Call', 'Jacuzzi'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 5 days before check-in.',
    'latitude': 13.3153,
    'longitude': 75.7754,
    'is_popular': true,
    'is_featured': true,
  },

  {
    'id': 'HTL-TN-001',
    'name': 'ITC Grand Chola',
    'destination': 'Chennai',
    'city': 'Chennai',
    'state': 'Tamil Nadu',
    'star_rating': 5,
    'address': 'No. 63, Mount Road, Guindy, Chennai, Tamil Nadu 600032',
    'rating': 4.9,
    'review_count': 1420,
    'price_per_night': 11899.0,
    'original_price': 14500.0,
    'images': [
      'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'A towering architectural monument honoring the imperial Chola dynasty, ITC Grand Chola in Chennai features hand-carved stone pillars, grand sweeping staircases, 10 acclaimed specialty restaurants, and the LEED Platinum Certified Kaya Kalp Royal Spa.',
    'amenities': [
      {'id': 'a1', 'name': 'Complimentary Ultra-Fast WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': '3 Spectacular Swimming Pools', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Kaya Kalp Royal Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Peshawri & Madras Pavilion', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Valet & Covered Parking', 'icon': 'parking'},
      {'id': 'a6', 'name': 'Executive Club Lounge', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-TN-001-1',
        'hotel_id': 'HTL-TN-001',
        'name': 'Executive Club Chola Room',
        'description': 'Dravidian luxury aesthetic, state-of-the-art in-room iPad controls, Italian marble bath with deep soak tub.',
        'price_per_night': 11899.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 430,
        'amenities': ['City View', 'Marble Bath', 'Smart Room Automation', 'Luxury Toiletries'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-TN-001-2',
        'hotel_id': 'HTL-TN-001',
        'name': 'Towers Luxury Presidential Suite',
        'description': 'Opulent multi-room suite with private board room, butler pantry, and access to the exclusive Towers Lounge.',
        'price_per_night': 21999.0,
        'capacity': 3,
        'bed_type': '1 King Bed',
        'size_sq_ft': 950,
        'amenities': ['Towers Lounge Access', 'Butler Service', 'Airport Chauffeur', 'Complimentary Cocktails'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to check-in.',
    'latitude': 13.0104,
    'longitude': 80.2206,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-TN-002',
    'name': 'Savoy - IHCL SeleQtions',
    'destination': 'Ooty',
    'city': 'Ooty',
    'state': 'Tamil Nadu',
    'star_rating': 5,
    'address': '77 Sylks Road, Ooty, Tamil Nadu 643001',
    'rating': 4.7,
    'review_count': 682,
    'price_per_night': 7999.0,
    'original_price': 9900.0,
    'images': [
      'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
    ],
    'description':
        'A historic 180-year-old British colonial estate nestled in the Nilgiri hills, Savoy retains its original cottage charm with roaring log fireplaces, afternoon cream tea on the manicured lawns, and panoramic views of Ooty’s pine slopes.',
    'amenities': [
      {'id': 'a1', 'name': 'Free High-Speed WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Working Wood Fireplace', 'icon': 'check'},
      {'id': 'a3', 'name': 'Ayurvedic Treatment Room', 'icon': 'spa'},
      {'id': 'a4', 'name': 'The Dining Room & English Lounge', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Heritage Afternoon Tea on Lawns', 'icon': 'check'},
      {'id': 'a6', 'name': 'Croquet & Billiards Room', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-TN-002-1',
        'hotel_id': 'HTL-TN-002',
        'name': 'Heritage Colonial Room',
        'description': 'Period rosewood furnishings, brass four-poster bed, wood fireplace lit daily, and flower garden access.',
        'price_per_night': 7999.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 440,
        'amenities': ['Garden View', 'Wood Fireplace', 'Heated Blanket', 'Nilgiri Herbal Tea'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
      {
        'id': 'RM-TN-002-2',
        'hotel_id': 'HTL-TN-002',
        'name': 'Savoy Heritage Garden Suite',
        'description': 'Spacious two-room suite with private sitting room, antique bay windows, log fireplace, and portico patio.',
        'price_per_night': 12499.0,
        'capacity': 3,
        'bed_type': '1 King Bed + 1 Daybed',
        'size_sq_ft': 720,
        'amenities': ['Private Portico', 'Living Room', 'Clawfoot Tub', 'Complimentary Afternoon Tea'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 72 hours prior to arrival.',
    'latitude': 11.4116,
    'longitude': 76.6957,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-TN-003',
    'name': 'Heritage Madurai',
    'destination': 'Madurai',
    'city': 'Madurai',
    'state': 'Tamil Nadu',
    'star_rating': 5,
    'address': '11 Melakkal Main Road, Kochadai, Madurai, Tamil Nadu 625016',
    'rating': 4.7,
    'review_count': 512,
    'price_per_night': 4899.0,
    'original_price': 6200.0,
    'images': [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Designed by world-renowned architect Geoffrey Bawa on 17 verdant acres shaded by 200-year-old banyan trees, Heritage Madurai features an Olympic-sized temple-tank swimming pool, Chettinad stone craftsmanship, and serene courtyard plunge pool villas.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast Free WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Temple Tank Architectural Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ayurvedic Treatment Center', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Banyan Restaurant & Chettinad Kitchen', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Meenakshi Amman Temple Tour Desk', 'icon': 'check'},
      {'id': 'a6', 'name': 'Free Valet Parking', 'icon': 'parking'},
    ],
    'rooms': [
      {
        'id': 'RM-TN-003-1',
        'hotel_id': 'HTL-TN-003',
        'name': 'Deluxe Club Heritage Room',
        'description': 'Open plan design with polished Athangudi floor tiles, private sit-out overlooking banyan canopy, and open shower.',
        'price_per_night': 4899.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 420,
        'amenities': ['Banyan Garden View', 'Veranda', 'Open-Air Shower', 'Tea Station'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-TN-003-2',
        'hotel_id': 'HTL-TN-003',
        'name': 'Private Plunge Pool Courtyard Villa',
        'description': 'Individual villa built inside high granite compound with personal plunge pool, open-sky courtyard, and daybed.',
        'price_per_night': 8499.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 700,
        'amenities': ['Private Plunge Pool', 'Granite Courtyard', 'Rain Shower', 'Complimentary Breakfast'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to check-in.',
    'latitude': 9.9392,
    'longitude': 78.0841,
    'is_popular': false,
    'is_featured': true,
  },
  {
    'id': 'HTL-TN-004',
    'name': 'The Carlton Kodaikanal',
    'destination': 'Kodaikanal',
    'city': 'Kodaikanal',
    'state': 'Tamil Nadu',
    'star_rating': 5,
    'address': 'Lake Road, Kodaikanal, Tamil Nadu 624101',
    'rating': 4.6,
    'review_count': 640,
    'price_per_night': 6499.0,
    'original_price': 8000.0,
    'images': [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
    ],
    'description':
        'The only five-star luxury resort situated right on the banks of pristine Kodaikanal Lake, The Carlton features manicured terraced flower gardens, private lake pedal boating, roaring hearths, and crisp misty mountain air.',
    'amenities': [
      {'id': 'a1', 'name': 'Complimentary High Speed WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Steam, Sauna & Jacuzzi Facility', 'icon': 'spa'},
      {'id': 'a3', 'name': 'Silver Oak Fine Dining Restaurant', 'icon': 'restaurant'},
      {'id': 'a4', 'name': 'Private Shikara & Pedal Boating Dock', 'icon': 'check'},
      {'id': 'a5', 'name': 'Golf Course & Outdoor Badminton', 'icon': 'check'},
      {'id': 'a6', 'name': 'Free Valet Parking', 'icon': 'parking'},
    ],
    'rooms': [
      {
        'id': 'RM-TN-004-1',
        'hotel_id': 'HTL-TN-004',
        'name': 'Deluxe Lake View Room',
        'description': 'Bright room with private step-out balcony overlooking the glistening Kodaikanal lake waters and hills.',
        'price_per_night': 6499.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 400,
        'amenities': ['Lake View', 'Private Balcony', 'Central Heating', 'Herbal Tea Caddy'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-TN-004-2',
        'hotel_id': 'HTL-TN-004',
        'name': 'Carlton Lakefront Cottage Suite',
        'description': 'Independent hillside cottage with direct lawn access, working fireplace, and panoramic lake view bay windows.',
        'price_per_night': 10499.0,
        'capacity': 3,
        'bed_type': '1 King Bed + 1 Rollaway',
        'size_sq_ft': 680,
        'amenities': ['Panoramic Lake View', 'Fireplace', 'Living Room', 'Fruit & Wine Basket'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 72 hours prior to arrival.',
    'latitude': 10.2381,
    'longitude': 77.4892,
    'is_popular': true,
    'is_featured': false,
  },
  {
    'id': 'HTL-TN-005',
    'name': 'Radisson Blu Coimbatore',
    'destination': 'Coimbatore',
    'city': 'Coimbatore',
    'state': 'Tamil Nadu',
    'star_rating': 4,
    'address': 'Avinashi Road, Peelamedu, Coimbatore, Tamil Nadu 641004',
    'rating': 4.4,
    'review_count': 418,
    'price_per_night': 4199.0,
    'original_price': 5200.0,
    'images': [
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Ideally located along bustling Avinashi Road near the airport, Radisson Blu Coimbatore offers sleek modern rooms, a scenic rooftop infinity pool overlooking the city, an authentic Kongunadu culinary menu, and 24-hour business facilities.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast Free Fiber WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Rooftop Infinity Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Serene Spa & Steam Room', 'icon': 'spa'},
      {'id': 'a4', 'name': 'The Great Kabab Factory & Seasons Cafe', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Complimentary Valet Parking', 'icon': 'parking'},
      {'id': 'a6', 'name': 'Airport Shuttle Service', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-TN-005-1',
        'hotel_id': 'HTL-TN-005',
        'name': 'Superior King City Room',
        'description': 'Contemporary design with soundproof floor-to-ceiling windows, ergonomic workstation, and plush bedding.',
        'price_per_night': 4199.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 350,
        'amenities': ['City Skyline View', 'Rain Shower', 'Tea/Coffee Station', 'Iron & Board'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-TN-005-2',
        'hotel_id': 'HTL-TN-005',
        'name': 'Business Class Junior Suite',
        'description': 'Corner suite with separate conversation lounge, Nespresso coffee system, and complimentary evening snacks.',
        'price_per_night': 6599.0,
        'capacity': 3,
        'bed_type': '1 King Bed',
        'size_sq_ft': 550,
        'amenities': ['Lounge Access', 'Bathtub', 'Nespresso Coffee', 'Free Airport Drop'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 24 hours prior to check-in.',
    'latitude': 11.0267,
    'longitude': 77.0125,
    'is_popular': false,
    'is_featured': false,
  },
  {
    'id': 'HTL-TN-006',
    'name': 'Palais de Mahe - CGH Earth',
    'destination': 'Puducherry',
    'city': 'Puducherry',
    'state': 'Tamil Nadu',
    'star_rating': 5,
    'address': '4 Bussy Street, White Town, Puducherry 605001',
    'rating': 4.8,
    'review_count': 492,
    'price_per_night': 9499.0,
    'original_price': 12000.0,
    'images': [
      'https://images.unsplash.com/photo-1549294413-26f195200c16?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Located in the heart of the historic French Quarter just 50 meters from the Promenade beach, Palais de Mahe combines traditional French colonial yellow-pillared verandas, a courtyard swimming pool, high arched doorways, and Franco-Tamil gourmet gastronomy.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast Free WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Central Courtyard Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ayurvedic Wellness Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Les Alizes Rooftop French Restaurant', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Steps to Promenade & Rock Beach', 'icon': 'check'},
      {'id': 'a6', 'name': 'Complimentary White Town Heritage Bicycles', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-TN-006-1',
        'hotel_id': 'HTL-TN-006',
        'name': 'Deluxe Colonnade Veranda Room',
        'description': 'Soaring ceilings, terracotta flooring, four-poster teak bed, and French doors opening onto the sunlit veranda.',
        'price_per_night': 9499.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 420,
        'amenities': ['Veranda Sit-Out', 'High Ceilings', 'Rain Shower', 'Organic Herbals'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
      {
        'id': 'RM-TN-006-2',
        'hotel_id': 'HTL-TN-006',
        'name': 'Palais Heritage Courtyard Suite',
        'description': 'Spacious French-Tamil salon with direct courtyard pool views, antique wooden armoires, and lounge sofa.',
        'price_per_night': 14999.0,
        'capacity': 3,
        'bed_type': '1 King Bed + 1 Daybed',
        'size_sq_ft': 680,
        'amenities': ['Pool View', 'Private Living Area', 'Clawfoot Bath', 'French Pastry Welcome'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 72 hours prior to arrival.',
    'latitude': 11.9318,
    'longitude': 79.8336,
    'is_popular': true,
    'is_featured': true,
  },

  {
    'id': 'HTL-KAR-007',
    'name': 'ITC Gardenia, A Luxury Collection Hotel',
    'destination': 'Bengaluru',
    'city': 'Bengaluru',
    'state': 'Karnataka',
    'star_rating': 5,
    'address': '1 Residency Road, Shanthala Nagar, Ashok Nagar, Bengaluru, Karnataka 560025',
    'rating': 4.8,
    'review_count': 1140,
    'price_per_night': 14200.0,
    'original_price': 17500.0,
    'images': [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
    ],
    'description':
        'Inspired by the garden city ethos of Bengaluru, ITC Gardenia is a LEED Platinum certified luxury haven nestled in the central business district. Features the world-renowned Kaya Kalp Spa and iconic restaurants including Edo and Kebabs & Kurries.',
    'amenities': [
      {'id': 'a1', 'name': 'High-Speed Premium WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Rooftop Heated Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Kaya Kalp Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Kebabs & Kurries & Edo Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Executive Lounge & Valet', 'icon': 'parking'},
      {'id': 'a6', 'name': '24-Hour Fitness Studio', 'icon': 'fitness'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-007-1',
        'hotel_id': 'HTL-KAR-007',
        'name': 'Tower Luxury King Room',
        'description': 'Contemporary luxury room with private sit-out terrace and panoramic garden city vistas.',
        'price_per_night': 14200.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 510,
        'amenities': ['Balcony', 'Deep Soak Tub', 'Smart Workstation', 'High-Speed WiFi'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
      {
        'id': 'RM-KAR-007-2',
        'hotel_id': 'HTL-KAR-007',
        'name': 'Flamingo Presidential Suite',
        'description': 'Bi-level master suite with glass-roofed private pool, steam shower, and dedicated butler.',
        'price_per_night': 28500.0,
        'capacity': 3,
        'bed_type': '1 Grand King Bed',
        'size_sq_ft': 1200,
        'amenities': ['Private Plunge Pool', 'Personal Butler', 'Airport Limousine', 'Steam Shower'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to check-in.',
    'latitude': 12.9667,
    'longitude': 77.5963,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-KAR-008',
    'name': 'The Oberoi, Bengaluru',
    'destination': 'Bengaluru',
    'city': 'Bengaluru',
    'state': 'Karnataka',
    'star_rating': 5,
    'address': '37-39 MG Road, Yellappa Garden, Sivanchetti Gardens, Bengaluru, Karnataka 560001',
    'rating': 4.9,
    'review_count': 980,
    'price_per_night': 16500.0,
    'original_price': 20000.0,
    'images': [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Built around a centenarian raintree in the heart of MG Road, The Oberoi Bengaluru is famous for lush tropical gardens, private balcony rooms with garden views, and award-winning Thai and contemporary French restaurants.',
    'amenities': [
      {'id': 'a1', 'name': 'High-Speed Fiber WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Outdoor Garden Swimming Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'The Oberoi Spa & Salon', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Rim Naam & Le Jardin Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Complimentary Valet Parking', 'icon': 'parking'},
      {'id': 'a6', 'name': 'Personalised Oberoi Butler', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-008-1',
        'hotel_id': 'HTL-KAR-008',
        'name': 'Premier Garden View Room',
        'description': 'Private balcony looking into century-old banyan trees and tranquil ornamental pond.',
        'price_per_night': 16500.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 540,
        'amenities': ['Garden Balcony', 'Pillow Menu', 'Marble Bathroom', 'Nespresso Machine'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 24 hours prior to arrival.',
    'latitude': 12.9738,
    'longitude': 77.6200,
    'is_popular': true,
    'is_featured': false,
  },
  {
    'id': 'HTL-KAR-009',
    'name': 'JW Marriott Hotel Bengaluru',
    'destination': 'Bengaluru',
    'city': 'Bengaluru',
    'state': 'Karnataka',
    'star_rating': 5,
    'address': '24/1 Vittal Mallya Rd, KG Halli, Shanthala Nagar, Ashok Nagar, Bengaluru, Karnataka 560001',
    'rating': 4.7,
    'review_count': 1320,
    'price_per_night': 13500.0,
    'original_price': 16000.0,
    'images': [
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    ],
    'description':
        'Overlooking the 300-acre green canopy of Cubbon Park and adjacent to UB City luxury mall, JW Marriott Bengaluru provides ultra-modern rooms, open-air Italian restaurant Alba, and a luxurious rooftop pool lounge.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast Free WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Heated Outdoor Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Spa by JW', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Alba & JW Kitchen', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Cubbon Park Facing Suites', 'icon': 'check'},
      {'id': 'a6', 'name': 'Full Fitness Center', 'icon': 'fitness'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-009-1',
        'hotel_id': 'HTL-KAR-009',
        'name': 'Cubbon Park View Deluxe',
        'description': 'Floor-to-ceiling windows with picturesque tree-top views of Cubbon Park and marble bathroom.',
        'price_per_night': 13500.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 480,
        'amenities': ['Cubbon Park View', 'Aromatherapy Amenities', 'Bathtub', 'High-Speed WiFi'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours before check-in.',
    'latitude': 12.9719,
    'longitude': 77.5960,
    'is_popular': false,
    'is_featured': true,
  },

  {
    'id': 'HTL-KER-009',
    'name': 'Brunton Boatyard - CGH Earth',
    'destination': 'Kochi',
    'city': 'Kochi',
    'state': 'Kerala',
    'star_rating': 5,
    'address': '1/498 Calvathy Road, Fort Kochi, Kochi, Kerala 682001',
    'rating': 4.9,
    'review_count': 640,
    'price_per_night': 11200.0,
    'original_price': 14000.0,
    'images': [
      'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Reconstructed from a 19th-century Victorian shipbuilding yard on the Fort Kochi harbor, Brunton Boatyard celebrates the Dutch, Portuguese, and British maritime heritage with sea-facing suites and legendary First Class Dining.',
    'amenities': [
      {'id': 'a1', 'name': 'Complimentary Harbor WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Harbor View Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ayurvedic Wellness Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Armoury & History Restaurant', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Daily Sunset Harbor Cruises', 'icon': 'check'},
      {'id': 'a6', 'name': 'Heritage Walking Tours', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-009-1',
        'hotel_id': 'HTL-KER-009',
        'name': 'Sea Facing Heritage Suite',
        'description': 'Four-poster teak bed, vintage terracotta floor, and private balcony overlooking ships entering Cochin harbor.',
        'price_per_night': 11200.0,
        'capacity': 2,
        'bed_type': '1 King Four-Poster Bed',
        'size_sq_ft': 520,
        'amenities': ['Harbor View', 'Antique Furniture', 'Clawfoot Tub', 'Sunset Cruise Included'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to arrival.',
    'latitude': 9.9678,
    'longitude': 76.2429,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-KER-010',
    'name': 'Fragrant Nature Kochi',
    'destination': 'Kochi',
    'city': 'Kochi',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Near Bazaar Road, Calvathy, Fort Kochi, Kochi, Kerala 682001',
    'rating': 4.7,
    'review_count': 510,
    'price_per_night': 7800.0,
    'original_price': 9500.0,
    'images': [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
    ],
    'description':
        'A boutique 5-star heritage masterpiece in Fort Kochi showcasing monumental Kerala mural art, a rooftop swimming pool with Arabian Sea sunset views, and state-of-the-art Ayurvedic wellness packages.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast WiFi in All Areas', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Rooftop Arabian Sea Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Prana Ayurveda Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Flint House & East India Cafe', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Art Gallery & Murals', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-010-1',
        'hotel_id': 'HTL-KER-010',
        'name': 'Duke’s Heritage Chamber',
        'description': 'Hand-painted murals, Victorian fittings, high ceilings, and garden or harbor glimpses.',
        'price_per_night': 7800.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 430,
        'amenities': ['Mural Art', 'Rain Shower', 'Espresso Machine', 'Air Conditioning'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours before check-in.',
    'latitude': 9.9654,
    'longitude': 76.2467,
    'is_popular': false,
    'is_featured': false,
  },
  {
    'id': 'HTL-KER-011',
    'name': 'Trident Hotel Cochin',
    'destination': 'Kochi',
    'city': 'Kochi',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Bristow Road, Willingdon Island, Kochi, Kerala 682003',
    'rating': 4.6,
    'review_count': 720,
    'price_per_night': 6500.0,
    'original_price': 8200.0,
    'images': [
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    ],
    'description':
        'Set on peaceful Willingdon Island amidst landscaped gardens and palm groves, Trident Cochin offers tranquil resort living close to Fort Kochi and business hubs, with authentic Kerala seafood specialty dining at Travancore.',
    'amenities': [
      {'id': 'a1', 'name': 'Free Wi-Fi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Landscaped Garden Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Trident Wellness Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Travancore & The Seafood Grill', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Free Island Parking', 'icon': 'parking'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-011-1',
        'hotel_id': 'HTL-KER-011',
        'name': 'Deluxe Garden Room',
        'description': 'Cozy room with warm wooden accents and views of tropical gardens and outdoor pool.',
        'price_per_night': 6500.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 380,
        'amenities': ['Garden View', 'Minibar', 'Smart TV', 'Room Service'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 24 hours prior to check-in.',
    'latitude': 9.9472,
    'longitude': 76.2731,
    'is_popular': false,
    'is_featured': false,
  },
  {
    'id': 'HTL-KER-012',
    'name': 'Vivanta Marine Drive Kochi',
    'destination': 'Kochi',
    'city': 'Kochi',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Shanmugham Road, Marine Drive, Ernakulam, Kochi, Kerala 682031',
    'rating': 4.7,
    'review_count': 890,
    'price_per_night': 7200.0,
    'original_price': 9000.0,
    'images': [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Perched right on Kochi’s scenic Marine Drive promenade overlooking Vembanad Lake and the harbor, Vivanta Kochi features contemporary high-rise luxury, a rooftop infinity pool, and the vibrant Jiva Spa.',
    'amenities': [
      {'id': 'a1', 'name': 'High-Speed WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Rooftop Infinity Harbor Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Jiva Ayurveda Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'The Sian & Latitude Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Marine Drive Walkway Access', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-012-1',
        'hotel_id': 'HTL-KER-012',
        'name': 'Superior Charm Backwater View',
        'description': 'Chic contemporary design with direct views over Marine Drive backwaters and passing boats.',
        'price_per_night': 7200.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 400,
        'amenities': ['Backwater View', 'Ergonomic Workstation', 'Rain Shower', 'Complimentary WiFi'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours before check-in.',
    'latitude': 9.9798,
    'longitude': 76.2764,
    'is_popular': true,
    'is_featured': false,
  },

  {
    'id': 'HTL-KER-013',
    'name': 'Blanket Hotel & Spa',
    'destination': 'Munnar',
    'city': 'Munnar',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Attukad Waterfalls, Aluva - Munnar Road, Pallivasal, Munnar, Kerala 685565',
    'rating': 4.9,
    'review_count': 780,
    'price_per_night': 7999.0,
    'original_price': 10500.0,
    'images': [
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    ],
    'description':
        'Nestled directly facing the spectacular Attukad Waterfalls in Munnar, Blanket Hotel is an eco-luxury retreat where every single room opens to views of cascading mountain waters and tea plantations.',
    'amenities': [
      {'id': 'a1', 'name': 'High Speed WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Waterfall View Infinity Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Blanket Ayurvedic Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Falls View All-Day Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Tea Garden Trekking & Birdwatching', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-013-1',
        'hotel_id': 'HTL-KER-013',
        'name': 'Blanket Waterfall Valley Suite',
        'description': 'Spacious room with floor-to-ceiling glass doors opening directly onto the roaring Attukad Waterfalls.',
        'price_per_night': 7999.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 460,
        'amenities': ['Waterfall View', 'Private Balcony', 'Jacuzzi', 'Fireplace'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to arrival.',
    'latitude': 10.0520,
    'longitude': 77.0430,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-KER-014',
    'name': 'Chandys Windy Woods',
    'destination': 'Munnar',
    'city': 'Munnar',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Chithirapuram Post, Pallivasal, Munnar, Kerala 685565',
    'rating': 4.8,
    'review_count': 690,
    'price_per_night': 6899.0,
    'original_price': 8900.0,
    'images': [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    ],
    'description':
        'Tiered into the mist-covered hills like a hanging garden, Chandys Windy Woods features artificial forest interiors, terrace greenery on every floor, and sweeping vistas of the Chithirapuram tea hills.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Hilltop Heated Swimming Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Spa & Steam Wellness', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Multicuisine Mountain Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Indoor Games & Bonfire', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-014-1',
        'hotel_id': 'HTL-KER-014',
        'name': 'Windy Woods Deluxe Suite',
        'description': 'Glass-walled terrace room offering unmatched sunrise views over the rolling green ridges.',
        'price_per_night': 6899.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 420,
        'amenities': ['Mountain Panorama', 'Private Terrace', 'Soaking Tub', 'Complimentary Breakfast'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours before check-in.',
    'latitude': 10.0380,
    'longitude': 77.0290,
    'is_popular': false,
    'is_featured': false,
  },
  {
    'id': 'HTL-KER-015',
    'name': 'The Panoramic Getaway',
    'destination': 'Munnar',
    'city': 'Munnar',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Munnar Bypass Road, Chithirapuram, Munnar, Kerala 685565',
    'rating': 4.7,
    'review_count': 540,
    'price_per_night': 8499.0,
    'original_price': 11000.0,
    'images': [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    ],
    'description':
        'Famous for its dual rooftop heated infinity pools over looking the sunset valleys, The Panoramic Getaway offers climate-controlled luxury rooms, helipad access, and signature international dining.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast Free WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Two Rooftop Heated Pools', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Tattvam Holistic Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Aiming Heights & Underground Grill', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Helipad Facility', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-015-1',
        'hotel_id': 'HTL-KER-015',
        'name': 'Panoramic Sunset Pavillion',
        'description': 'Motorized curtains, private jacuzzi on the balcony, and front-row seats to Munnar sunsets.',
        'price_per_night': 8499.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 490,
        'amenities': ['Balcony Jacuzzi', 'Sunset View', 'Smart Lighting', 'Minibar'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 72 hours prior to arrival.',
    'latitude': 10.0290,
    'longitude': 77.0180,
    'is_popular': false,
    'is_featured': true,
  },

  {
    'id': 'HTL-KER-016',
    'name': 'Mountain Shadows Resort',
    'destination': 'Wayanad',
    'city': 'Wayanad',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Padinjarathara, Kuttiyamvayal, Wayanad, Kerala 673575',
    'rating': 4.9,
    'review_count': 620,
    'price_per_night': 12500.0,
    'original_price': 16000.0,
    'images': [
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    ],
    'description':
        'Surrounded on three sides by the azure waters of Banasura Sagar reservoir and ancient Western Ghat rainforests, Mountain Shadows offers isolated luxury pool cottages and lakeside wellness.',
    'amenities': [
      {'id': 'a1', 'name': 'Island High-Speed WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Reservoir Infinity Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Vaidya Ayurveda Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Lakeside Fine Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Kayaking & Speedboat Safaris', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-016-1',
        'hotel_id': 'HTL-KER-016',
        'name': 'Private Lakefront Pool Villa',
        'description': 'Secluded cottage with private plunge pool directly overlooking the mist-covered Banasura lake waters.',
        'price_per_night': 12500.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 600,
        'amenities': ['Private Plunge Pool', 'Lakefront Deck', 'Deep Bathtub', 'High-Speed WiFi'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours before check-in.',
    'latitude': 11.6680,
    'longitude': 75.9520,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-KER-017',
    'name': 'Morickap Resort',
    'destination': 'Wayanad',
    'city': 'Wayanad',
    'state': 'Kerala',
    'star_rating': 5,
    'address': 'Banasura Sagar Dam Road, Pinangode, Pozhuthana, Wayanad, Kerala 673575',
    'rating': 4.7,
    'review_count': 490,
    'price_per_night': 9800.0,
    'original_price': 12500.0,
    'images': [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    ],
    'description':
        'Swiss-chalet inspired architectural resort perched on the highest ridge of Pinangode hills, offering panoramic 360-degree vistas of the Banasura mountains and cascading outdoor pools.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast Free WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Valley Edge Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ayurvedic Spa & Steam', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Clove All-Day Dining', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Mountain Biking Trails', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KER-017-1',
        'hotel_id': 'HTL-KER-017',
        'name': 'Morickap Studio Jacuzzi Suite',
        'description': 'Chalet suite with open-air jacuzzi on wooden deck overlooking lush evergreen tea plantations.',
        'price_per_night': 9800.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 510,
        'amenities': ['Private Balcony Jacuzzi', 'Mountain View', 'Tea Station', 'Air Conditioning'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours prior to arrival.',
    'latitude': 11.6420,
    'longitude': 75.9890,
    'is_popular': false,
    'is_featured': false,
  },

  {
    'id': 'HTL-KAR-010',
    'name': 'The Tamara Coorg',
    'destination': 'Coorg',
    'city': 'Madikeri',
    'state': 'Karnataka',
    'star_rating': 5,
    'address': 'Kabbinakad Estate, Napoklu Nad, Yavakapadi Village, Coorg, Karnataka 571214',
    'rating': 4.9,
    'review_count': 910,
    'price_per_night': 18500.0,
    'original_price': 23000.0,
    'images': [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
    ],
    'description':
        'Set inside a 180-acre private organic coffee and cardamom plantation on the slopes of the Western Ghats, The Tamara features stilted wooden luxury cottages, crystalline mountain streams, and the elevated deck restaurant The Falls.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast Cottage WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Outdoor Heated Forest Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'The Elevation Spa', 'icon': 'spa'},
      {'id': 'a4', 'name': 'The Falls & Deck Multi-Cuisine', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Coffee Blending Workshop & Walks', 'icon': 'check'},
      {'id': 'a6', 'name': 'Yoga Temple by the Waterfall', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-010-1',
        'hotel_id': 'HTL-KAR-010',
        'name': 'Luxury Forest Stilt Cottage',
        'description': 'Elevated stilted wooden villa built above plantation canopies with sundeck and forest breeze.',
        'price_per_night': 18500.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 620,
        'amenities': ['Private Sun Deck', 'Panoramic Forest View', 'Espresso Machine', 'Heated Shower'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 72 hours prior to arrival.',
    'latitude': 12.2150,
    'longitude': 75.7190,
    'is_popular': true,
    'is_featured': true,
  },
  {
    'id': 'HTL-KAR-011',
    'name': 'Heritage Resort Coorg',
    'destination': 'Coorg',
    'city': 'Madikeri',
    'state': 'Karnataka',
    'star_rating': 4,
    'address': '50/3, 1st Monnangeri Village, Galibeedu, Madikeri, Coorg, Karnataka 571201',
    'rating': 4.6,
    'review_count': 580,
    'price_per_night': 7500.0,
    'original_price': 9800.0,
    'images': [
      'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?w=800&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
    ],
    'description':
        'Perched atop a breezy cliff in Madikeri offering dramatic cloudscapes and coffee valley views, Heritage Resort features Kodagu heritage architecture, Ayurveda treatments, and bonfire evenings.',
    'amenities': [
      {'id': 'a1', 'name': 'Free Wi-Fi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Hilltop Swimming Pool', 'icon': 'pool'},
      {'id': 'a3', 'name': 'Ayur Spa Therapy', 'icon': 'spa'},
      {'id': 'a4', 'name': 'Kodagu Traditional Kitchen', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Evening Campfire & Music', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-KAR-011-1',
        'hotel_id': 'HTL-KAR-011',
        'name': 'Estate Cottage Deluxe',
        'description': 'Traditional tile-roof cottage with private sitout facing endless coffee plantations.',
        'price_per_night': 7500.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 400,
        'amenities': ['Estate Sitout', 'Coffee Maker', 'Hot Shower', 'Flat-screen TV'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours before check-in.',
    'latitude': 12.4430,
    'longitude': 75.7320,
    'is_popular': false,
    'is_featured': false,
  },

  {
    'id': 'HTL-TN-007',
    'name': 'Fortune Resort Sullivan Court',
    'destination': 'Ooty',
    'city': 'Ooty',
    'state': 'Tamil Nadu',
    'star_rating': 4,
    'address': '1 Selborne Road, Ooty, Tamil Nadu 643001',
    'rating': 4.6,
    'review_count': 670,
    'price_per_night': 6200.0,
    'original_price': 8000.0,
    'images': [
      'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Named as a tribute to John Sullivan the founder of Ooty, this scenic hill resort sits on landscaped green slopes offering colonial ambiance, sauna wellness, and family recreational lawns.',
    'amenities': [
      {'id': 'a1', 'name': 'Fast Free WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Sauna & Steam Wellness', 'icon': 'spa'},
      {'id': 'a3', 'name': 'Pavilion All-Day Dining', 'icon': 'restaurant'},
      {'id': 'a4', 'name': 'Billiards & Table Tennis', 'icon': 'check'},
      {'id': 'a5', 'name': 'Bonfire & Barbecue Nights', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-TN-007-1',
        'hotel_id': 'HTL-TN-007',
        'name': 'Sullivan Superior Room',
        'description': 'Warm wooden paneling, large windows facing pine slopes, and room heater.',
        'price_per_night': 6200.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 360,
        'amenities': ['Pine Hill View', 'Room Heater', 'Tea Maker', 'Satellite TV'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 24 hours prior to arrival.',
    'latitude': 11.4080,
    'longitude': 76.7110,
    'is_popular': true,
    'is_featured': false,
  },
  {
    'id': 'HTL-TN-008',
    'name': 'Sinclairs Retreat Ooty',
    'destination': 'Ooty',
    'city': 'Ooty',
    'state': 'Tamil Nadu',
    'star_rating': 4,
    'address': 'Gorishola Road, Ooty, Tamil Nadu 643001',
    'rating': 4.7,
    'review_count': 530,
    'price_per_night': 7100.0,
    'original_price': 9000.0,
    'images': [
      'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800&q=80',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    'description':
        'Perched at an altitude of nearly 8,000 feet, Sinclairs Retreat is Ooty’s highest resort offering breathtaking sunrise views over the Blue Mountains and the Nilgiri valley below.',
    'amenities': [
      {'id': 'a1', 'name': 'Complimentary WiFi', 'icon': 'wifi'},
      {'id': 'a2', 'name': 'Altitude View Decks', 'icon': 'check'},
      {'id': 'a3', 'name': 'Pine Forest Spa & Steam', 'icon': 'spa'},
      {'id': 'a4', 'name': 'High Point Multi-Cuisine', 'icon': 'restaurant'},
      {'id': 'a5', 'name': 'Library & Indoor Games', 'icon': 'check'},
    ],
    'rooms': [
      {
        'id': 'RM-TN-008-1',
        'hotel_id': 'HTL-TN-008',
        'name': 'Highland View Deluxe Room',
        'description': 'Attic-style timber ceiling with uninterrupted valley vistas of Nilgiri mountains.',
        'price_per_night': 7100.0,
        'capacity': 2,
        'bed_type': '1 King Bed',
        'size_sq_ft': 390,
        'amenities': ['Nilgiri Mountain View', 'Room Heater', 'Wooden Ceilings', 'Hot Water Bath'],
        'is_available': true,
        'images': ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'],
      },
    ],
    'cancellation_policy': 'Free cancellation up to 48 hours before check-in.',
    'latitude': 11.4210,
    'longitude': 76.7260,
    'is_popular': false,
    'is_featured': true,
  },
];
