// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQbshzx53SCBrlJ3RG3km8fVNVlinG-D4',
    appId: '1:274482428373:web:c623c23d064ea82335255c',
    messagingSenderId: '274482428373',
    projectId: 'story-nest-8e84c',
    authDomain: 'story-nest-8e84c.firebaseapp.com',
    storageBucket: 'story-nest-8e84c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv3Szq1YT35AMTNvip_mo9WABdh6aZWVg',
    appId: '1:274482428373:android:c833200e611e2a9e35255c',
    messagingSenderId: '274482428373',
    projectId: 'story-nest-8e84c',
    storageBucket: 'story-nest-8e84c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVhIDXr_FzKi-gbztgZHJq1Br0WmpkZuU',
    appId: '1:274482428373:ios:0ca2dec55ec602ed35255c',
    messagingSenderId: '274482428373',
    projectId: 'story-nest-8e84c',
    storageBucket: 'story-nest-8e84c.firebasestorage.app',
    iosBundleId: 'com.example.nelegateAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVhIDXr_FzKi-gbztgZHJq1Br0WmpkZuU',
    appId: '1:274482428373:ios:0ca2dec55ec602ed35255c',
    messagingSenderId: '274482428373',
    projectId: 'story-nest-8e84c',
    storageBucket: 'story-nest-8e84c.firebasestorage.app',
    iosBundleId: 'com.example.nelegateAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkuJtWuHHy4WBhwDIffvM05dY1qn_1Ml8',
    appId: '1:274482428373:web:2febdb21eb3225de35255c',
    messagingSenderId: '274482428373',
    projectId: 'story-nest-8e84c',
    authDomain: 'story-nest-8e84c.firebaseapp.com',
    storageBucket: 'story-nest-8e84c.firebasestorage.app',
  );
}
